
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 146
#define YY_END_OF_BUFFER 147
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[334] =
    {   0,
        0,    0,  147,  146,  145,  128,  141,  146,  141,  141,
      142,  140,  138,  135,  141,   99,   97,   98,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,    0,  131,  131,  131,  131,  131,    0,
      141,    0,    0,  135,  141,  135,    0,    1,  138,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      123,  141,  141,  141,  101,   96,  100,  103,  141,  141,
      141,  141,  141,  141,    0,  144,  141,  141,  141,  141,

       96,  141,  141,  141,  141,  141,    0,    0,  103,  102,
      143,    0,  141,  130,    0,    0,    0,    0,    0,  123,
      134,  134,  134,    1,    1,  138,  118,   57,   69,   83,
      104,   92,   50,   66,  110,    3,  105,   43,   62,   74,
       81,   82,   19,   14,   36,   32,   16,   11,   77,   38,
       24,   27,   71,   97,   15,   33,  100,    2,   78,   98,
       85,   12,   47,   87,   40,   48,    8,   30,   31,   51,
       67,   70,   39,  101,   25,   34,   53,   99,   45,   89,
      118,   10,   65,    4,   91,   49,   84,   93,   42,   61,
       73,   88,   37,   18,  111,   26,   56,   63,   46,   64,

       23,   35,   41,    9,   44,   20,   13,   80,  107,  106,
       60,   76,   17,  114,   79,   75,   72,   28,   59,  109,
      113,   55,   54,   21,   58,   90,   68,   52,  108,   22,
       86,   29,  118,   96,  137,  136,  141,  141,  141,  124,
      123,  129,  141,  141,  141,  126,  141,  127,  141,  141,
      141,  132,  132,  132,  132,  132,  141,  141,  141,  141,
      141,  141,  141,  133,  133,  133,  133,  133,    0,  130,
      137,  136,    0,    0,    0,  124,  123,  139,  138,  121,
      121,  141,  141,  141,  125,  141,  141,  141,  122,  124,
      141,    6,    5,  141,  141,  141,  141,  141,  141,  141,

      141,  141,  112,  119,    0,    0,    0,  125,    0,    0,
        0,  122,  124,  125,  122,    7,  141,  112,  141,  116,
      141,  141,  141,  141,  125,  122,   94,  141,  141,  115,
      117,   95,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    6,    7,    8,    9,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,    1,   18,
       19,   20,   21,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,    9,   48,   48,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,   69,   70,   71,   72,
       73,   74,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   75,   75,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   75,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   76,   76,   76,    1,    1,   77,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   76,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   76,   75,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[78] =
    {   0,
        1,    1,    2,    3,    1,    4,    5,    6,    4,    4,
        1,    4,    7,    7,    4,    7,    4,    4,    3,    4,
        1,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    4,    3
    } ;

static yyconst flex_uint16_t yy_base[347] =
    {   0,
        0,    0,  604, 1219, 1219, 1219,    0,   71,   75,    0,
       69,   70,  135,   75,  190,   73, 1219,  581,  591,  572,
      574,  566,   58,   83,  517,  528,  506,  518,  504,   42,
       44,   95,    0,  545,  553,  109,  111,  113,  115,  551,
      237,   87,   94,  235,  111,  238,   72,  259,  540,  331,
      402,  456,  507,  556,  241,  603,  639,  686,  243,  255,
      729,  774,  317,  818,  867,  269,  401,  916,  967, 1013,
      329,  235,  407, 1057,  504,  537,  337,  517,  510,  479,
      478,  307,  338,  459, 1219,    0, 1219,    0,  489,  497,
      479,  488,  489,  461,  249, 1219,    0,  447,  439,  446,

      427,  425,  423,  438,  430,  434,  402,  463, 1219, 1219,
     1219,  468,  604,  646,  449,  408,  420,  418,  390,  388,
        0,  440,  438,    0,  696,  724,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      507,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  578,    0,  511,  514,  404,  403,  366,  362,
        0,    0,  114,  486,  626,    0,  395,    0,  385,  368,
      337,    0,  396,  395,  394,  393,  348,  323,  336,  335,
      314,  325,  310,    0,  368,  367,  366,  349,  330,  324,
      569,  734,  297,  296,  267,  266, 1219, 1051, 1117,    0,
      583,  292,  291,  263,  261,  283,  282,  252,  249,    0,
      660,    0,    0,  276,  269,  241,  222,  231,  215,  215,

      207,  215,  209, 1219,  223,  221,  192,  185,  209,  206,
       95,   93, 1219,    0,    0,    0,  105,    0,   83,    0,
       70,   84,   69,   66, 1219, 1219,    0,   66,   79,    0,
        0,    0, 1219, 1162, 1165, 1172,  122, 1179, 1183,  118,
      105, 1190, 1197, 1201, 1206, 1211
    } ;

static yyconst flex_int16_t yy_def[347] =
    {   0,
      333,    1,  333,  333,  333,  333,  334,  335,  334,  334,
      333,  334,  333,  334,  334,  334,  333,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  333,  335,  335,  335,  335,  335,  333,
      336,  333,  333,  333,  334,  334,  337,  338,  334,  339,
      339,   51,   51,   51,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,  334,  334,  334,  334,  334,
      334,   15,   15,   15,  333,  334,  333,  334,  334,  334,
      334,  334,  334,  334,  340,  333,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  341,  333,  333,  333,
      333,  342,  336,  336,  333,  333,  333,  333,  333,  333,
      337,  337,  337,  343,  338,  344,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      345,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  345,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,   15,   15,  334,  334,  334,  334,  334,
      334,  340,  340,  340,  340,  340,  334,  334,  334,  334,
      334,  334,  334,  341,  341,  341,  341,  341,  333,  342,
      333,  333,  333,  333,  333,  333,  333,  344,  344,  346,
      345,  334,  334,  334,  334,  334,  334,  334,  334,  334,
       15,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  333,  333,  334,  334,  334,  334,
      334,  334,    0,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333
    } ;

static yyconst flex_uint16_t yy_nxt[1297] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,    7,   10,
       11,    7,   12,   13,   10,   14,   15,   16,   17,   18,
        4,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   19,    7,   20,    7,   21,    7,    7,   22,
        7,    7,    7,   23,   24,    7,    7,    7,    7,    7,
       25,   26,   27,    7,    7,    7,    7,    7,    7,    7,
        7,   28,    7,    7,    7,   29,   30,    7,    7,    7,
       31,   32,    7,    7,    7,    7,    4,   34,   40,   42,
       41,   43,   45,   92,   44,   46,   76,   93,   77,   95,
       46,   85,   86,   96,  103,   97,  105,   42,   78,   43,

      106,  107,   44,   36,  122,   96,   43,   97,   79,   44,
      104,  264,   37,  123,   94,  333,  109,  333,  110,  333,
      109,  333,  110,   45,  252,   80,   46,  242,  121,  243,
       38,  332,  318,  327,  331,   81,  330,  329,  328,   39,
       33,   47,   33,   33,   48,  327,   33,   33,   49,   33,
       33,   33,   33,  326,   33,  326,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   72,
       72,   72,   33,   50,   51,   52,   53,   54,   73,   56,
       57,   58,   59,   60,   61,   74,   75,   64,   65,   66,

       67,   68,   69,   70,   71,   72,   72,   72,   72,   33,
       33,   82,   82,   82,   82,   83,   82,   82,   82,   82,
       82,   82,   82,   82,   84,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,  112,  112,  326,
      112,  112,  326,  112,  114,  325,  115,  112,  116,   76,
       44,   77,  325,   46,  325,  112,  325,  112,  117,  124,
      124,   78,  124,  124,  318,  124,  155,  127,  118,  124,
      324,   79,  127,  127,  323,  127,  156,  124,  127,  124,
      127,  253,  322,  321,  172,  119,  320,  127,   80,  319,
      254,  173,  127,  155,  127,  120,  318,  318,   81,  127,

      127,  127,  127,  156,  317,  127,  198,  127,  255,  315,
      199,  172,  315,  112,  127,  315,  315,  256,  173,  127,
      242,  314,  243,  314,  314,  314,  313,  313,  127,  313,
      313,  270,   82,  198,  304,  124,   33,  199,   33,   33,
       33,   82,   33,   33,   33,   33,   33,   33,   33,  127,
       33,  242,  236,  243,  127,  183,  110,  128,  230,  184,
      237,  127,  185,   82,  129,  130,  127,  231,  232,  131,
      238,  132,  244,  109,  110,  109,  127,  303,   33,  302,
      301,  127,  183,  300,  128,  230,  299,  239,  127,  185,
      298,  129,  130,  127,  231,  232,  131,  240,  132,  297,

      110,  109,  110,  109,  296,   33,   33,   33,  295,   33,
       33,   33,  294,   33,   33,   33,   33,   33,   33,   33,
      293,   33,  290,  272,  200,  133,  290,  201,  134,  202,
      203,  273,  155,  127,  265,  135,  290,  290,  127,  127,
      136,  274,  156,  266,  127,  110,  137,  109,  277,   33,
      277,  277,  133,  277,  201,  134,  202,  203,  275,  155,
      127,  267,  135,  165,  271,  127,  127,  136,  276,  156,
      268,  127,  242,  137,  243,  270,   33,   33,  138,  139,
      140,  141,  127,  269,   82,  263,  262,  261,  142,  127,
      248,  143,  260,   82,  127,  144,  145,  246,  259,  242,

      127,  243,  258,  257,  245,  138,  139,  140,  141,  127,
      280,   82,  251,  250,   33,  142,  127,  249,  143,  248,
       82,  127,  144,  145,  247,  280,  235,  127,  146,  236,
      147,  291,  246,  127,  282,  148,  127,  286,  241,  241,
      149,  127,  183,  241,  283,  150,  151,  287,  152,  185,
      241,  127,  235,  126,   33,  146,  234,  147,  111,  333,
      127,  284,  148,  127,  288,  108,  102,  149,  127,  183,
      101,  285,  150,  151,  289,  152,  185,  100,  127,  127,
       99,  280,  127,  280,  271,   33,  280,   98,  153,  127,
       33,   91,  305,  154,  127,   90,  280,   89,   88,   87,

      127,  280,  306,  333,  112,  112,  127,  112,  112,  127,
      112,  114,  333,  333,  112,  153,  127,  333,  333,  307,
      154,  127,  112,  333,  112,   33,  333,  127,  157,  308,
       33,  333,  333,  333,  333,  127,  333,  333,  158,  292,
      127,  243,  159,  160,  333,  333,  112,  112,  333,  112,
      112,   82,  112,  114,  280,  157,  112,  333,  333,  280,
       82,  333,  127,  333,  112,  158,  112,  127,  333,  159,
      160,  127,  333,  316,  333,  243,  127,  161,  162,  333,
      112,  333,  163,  333,  164,   82,  333,  333,  333,  333,
      333,  333,  333,  333,   82,  333,  124,  124,  127,  124,

      124,  333,  124,  127,  161,  162,  124,  333,  333,  163,
      333,  164,  165,  333,  124,  333,  124,  333,  166,  167,
      168,  333,  112,  127,  169,  170,  171,  333,  333,   33,
      333,   33,   33,   33,  333,   33,  333,  279,   33,  165,
       33,   33,  333,   33,  333,  166,  167,  168,  333,  272,
      127,  169,  170,  171,  174,  333,  333,  309,  175,  333,
      333,  176,  333,  333,  333,  333,  127,  310,  177,  178,
      333,   33,  124,  333,  333,  333,  333,  333,  333,  333,
      333,  174,  333,  333,  311,  175,  333,  333,  176,  333,
      333,  333,  333,  127,  312,  177,  178,  179,  333,  180,

      333,  181,  333,  333,  333,  333,  127,  333,  333,  333,
      333,  127,  333,  182,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  179,  333,  180,  333,  181,  333,
      333,  333,  333,  127,  333,  333,  333,  333,  127,  333,
      182,  186,  333,  333,  187,  188,  333,  189,  333,  333,
      127,  333,  190,  333,  333,  127,  191,  333,  333,  333,
      192,  333,  333,  333,  333,  333,  333,  333,  186,  333,
      333,  187,  188,  333,  189,  333,  333,  127,  333,  190,
      333,  333,  127,  191,  333,  333,  333,  192,  193,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  194,

      195,  196,  333,  333,  127,  333,  333,  333,  333,  333,
      197,  333,  333,  333,  333,  193,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  194,  195,  196,  333,
      333,  127,  333,  333,  333,  333,  333,  197,  204,  205,
      206,  207,  333,  333,  333,  333,  333,  208,  209,  333,
      333,  333,  210,  127,  333,  211,  333,  212,  333,  333,
      213,  333,  333,  333,  333,  204,  205,  206,  207,  333,
      333,  333,  333,  333,  208,  209,  333,  333,  333,  210,
      127,  333,  211,  333,  212,  333,  333,  213,  214,  215,
      333,  216,  333,  333,  333,  217,  218,  333,  333,  219,

      220,  333,  333,  221,  127,  222,  333,  333,  223,  333,
      333,  333,  333,  333,  333,  214,  215,  333,  216,  333,
      333,  333,  217,  218,  333,  333,  219,  220,  333,  333,
      221,  127,  222,  333,  333,  223,  224,  225,  333,  333,
      333,  333,  333,  333,  333,  226,  333,  227,  333,  228,
      127,  333,  229,  333,  333,  333,   33,  333,   33,   33,
       33,  333,   33,  224,  225,   33,  333,   33,   33,  333,
       33,  333,  226,  333,  227,  333,  228,  127,  333,  229,
      179,  333,  180,  333,  181,  333,  333,  333,  333,  127,
      333,  333,  333,  333,  127,  333,  182,  333,   33,  333,

      333,  333,  333,  333,  333,  333,  333,  179,  333,  180,
      333,  233,  333,  333,  333,  333,  127,  333,  333,  333,
      333,  127,   33,  182,   33,   33,   33,  333,   33,  333,
      279,   33,  333,   33,   33,  333,   33,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,   33,   33,  333,   33,   33,   35,
      333,   35,  113,  333,  113,  113,  113,  113,  113,  125,
      333,  125,  125,  125,  125,  125,  127,  333,  127,  127,
      112,  333,  112,  112,  112,  112,  112,  124,  333,  124,

      124,  124,  124,  124,  278,  333,  278,  278,  281,  281,
      333,  281,  281,  280,  280,  333,  333,  280,    3,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333

    } ;

static yyconst flex_int16_t yy_chk[1297] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    8,    9,   11,
        9,   11,   12,   23,   11,   12,   14,   23,   14,   24,
       14,   16,   16,   24,   30,   24,   31,   42,   14,   42,

       31,   32,   42,    8,   47,   32,   43,   32,   14,   43,
       30,  341,    8,   47,   23,   36,   36,   37,   37,   38,
       38,   39,   39,   45,  340,   14,   45,  243,  337,  243,
        8,  329,  328,  324,  323,   14,  322,  321,  319,    8,
       13,   13,   13,   13,   13,  317,   13,   13,   13,   13,
       13,   13,   13,  312,   13,  311,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   41,   41,  310,
       41,   41,  309,   41,   41,  308,   44,   41,   44,   46,
       44,   46,  307,   46,  306,   41,  305,   41,   44,   48,
       48,   46,   48,   48,  303,   48,   55,   72,   44,   48,
      302,   46,   72,   55,  301,   59,   55,   48,   55,   48,
       59,   95,  300,  299,   59,   44,  298,   60,   46,  297,
       95,   60,   60,   55,   72,   44,  296,  295,   46,   72,

       55,   66,   59,   55,  294,   55,   66,   59,   95,  289,
       66,   59,  288,   41,   60,  287,  286,   95,   60,   60,
       82,  285,   82,  284,  283,  282,  276,  275,   66,  274,
      273,  270,   82,   66,  269,   48,   50,   66,   50,   50,
       50,   82,   50,   50,   50,   50,   50,   50,   50,   63,
       50,   83,   77,   83,   63,   63,  268,   50,   71,   63,
       77,   71,   63,   83,   50,   50,   71,   71,   71,   50,
       77,   50,   83,  267,  266,  265,   63,  263,   50,  262,
      261,   63,   63,  260,   50,   71,  259,   77,   71,   63,
      258,   50,   50,   71,   71,   71,   50,   77,   50,  257,

      256,  255,  254,  253,  251,   50,   50,   51,  250,   51,
       51,   51,  249,   51,   51,   51,   51,   51,   51,   51,
      247,   51,  240,  116,   67,   51,  239,   67,   51,   67,
       67,  116,   73,   67,  107,   51,  238,  237,   67,   73,
       51,  116,   73,  107,   73,  123,   51,  122,  120,   51,
      119,  118,   51,  117,   67,   51,   67,   67,  116,   73,
       67,  107,   51,   73,  115,   67,   73,   51,  116,   73,
      107,   73,   84,   51,   84,  112,   51,   51,   52,   52,
       52,   52,   52,  108,   84,  106,  105,  104,   52,   52,
      103,   52,  102,   84,   52,   52,   52,  101,  100,  244,

       52,  244,   99,   98,   84,   52,   52,   52,   52,   52,
      181,  244,   94,   93,  181,   52,   52,   92,   52,   91,
      244,   52,   52,   52,   90,  181,  235,   52,   53,  236,
       53,  244,   89,   53,  235,   53,   75,  236,   81,   80,
       53,   75,   75,   79,  235,   53,   53,  236,   53,   75,
       78,   53,   76,   49,  181,   53,   75,   53,   40,   35,
       53,  235,   53,   75,  236,   34,   29,   53,   75,   75,
       28,  235,   53,   53,  236,   53,   75,   27,   53,   54,
       26,  233,   54,  181,  271,  233,  281,   25,   54,   54,
      281,   22,  271,   54,   54,   21,  233,   20,   19,   18,

       54,  281,  271,    3,  113,  113,   54,  113,  113,   54,
      113,  113,    0,    0,  113,   54,   54,    0,    0,  271,
       54,   54,  113,    0,  113,  233,    0,   54,   56,  271,
      281,    0,    0,    0,    0,   56,    0,    0,   56,  245,
       56,  245,   56,   56,    0,    0,  114,  114,    0,  114,
      114,  245,  114,  114,  233,   56,  114,    0,    0,  281,
      245,    0,   56,    0,  114,   56,  114,   56,    0,   56,
       56,   57,    0,  291,    0,  291,   57,   57,   57,    0,
      113,    0,   57,    0,   57,  291,    0,    0,    0,    0,
        0,    0,    0,    0,  291,    0,  125,  125,   57,  125,

      125,    0,  125,   57,   57,   57,  125,    0,    0,   57,
        0,   57,   58,    0,  125,    0,  125,    0,   58,   58,
       58,    0,  114,   58,   58,   58,   58,    0,    0,  126,
        0,  126,  126,  126,    0,  126,    0,  126,  126,   58,
      126,  126,    0,  126,    0,   58,   58,   58,    0,  272,
       58,   58,   58,   58,   61,    0,    0,  272,   61,    0,
        0,   61,    0,    0,    0,    0,   61,  272,   61,   61,
        0,  126,  125,    0,    0,    0,    0,    0,    0,    0,
        0,   61,    0,    0,  272,   61,    0,    0,   61,    0,
        0,    0,    0,   61,  272,   61,   61,   62,    0,   62,

        0,   62,    0,    0,    0,    0,   62,    0,    0,    0,
        0,   62,    0,   62,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   62,    0,   62,    0,   62,    0,
        0,    0,    0,   62,    0,    0,    0,    0,   62,    0,
       62,   64,    0,    0,   64,   64,    0,   64,    0,    0,
       64,    0,   64,    0,    0,   64,   64,    0,    0,    0,
       64,    0,    0,    0,    0,    0,    0,    0,   64,    0,
        0,   64,   64,    0,   64,    0,    0,   64,    0,   64,
        0,    0,   64,   64,    0,    0,    0,   64,   65,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   65,

       65,   65,    0,    0,   65,    0,    0,    0,    0,    0,
       65,    0,    0,    0,    0,   65,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   65,   65,   65,    0,
        0,   65,    0,    0,    0,    0,    0,   65,   68,   68,
       68,   68,    0,    0,    0,    0,    0,   68,   68,    0,
        0,    0,   68,   68,    0,   68,    0,   68,    0,    0,
       68,    0,    0,    0,    0,   68,   68,   68,   68,    0,
        0,    0,    0,    0,   68,   68,    0,    0,    0,   68,
       68,    0,   68,    0,   68,    0,    0,   68,   69,   69,
        0,   69,    0,    0,    0,   69,   69,    0,    0,   69,

       69,    0,    0,   69,   69,   69,    0,    0,   69,    0,
        0,    0,    0,    0,    0,   69,   69,    0,   69,    0,
        0,    0,   69,   69,    0,    0,   69,   69,    0,    0,
       69,   69,   69,    0,    0,   69,   70,   70,    0,    0,
        0,    0,    0,    0,    0,   70,    0,   70,    0,   70,
       70,    0,   70,    0,    0,    0,  278,    0,  278,  278,
      278,    0,  278,   70,   70,  278,    0,  278,  278,    0,
      278,    0,   70,    0,   70,    0,   70,   70,    0,   70,
       74,    0,   74,    0,   74,    0,    0,    0,    0,   74,
        0,    0,    0,    0,   74,    0,   74,    0,  278,    0,

        0,    0,    0,    0,    0,    0,    0,   74,    0,   74,
        0,   74,    0,    0,    0,    0,   74,    0,    0,    0,
        0,   74,  279,   74,  279,  279,  279,    0,  279,    0,
      279,  279,    0,  279,  279,    0,  279,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  279,  334,    0,  334,  334,  335,
        0,  335,  336,    0,  336,  336,  336,  336,  336,  338,
        0,  338,  338,  338,  338,  338,  339,    0,  339,  339,
      342,    0,  342,  342,  342,  342,  342,  343,    0,  343,

      343,  343,  343,  343,  344,    0,  344,  344,  345,  345,
        0,  345,  345,  346,  346,    0,    0,  346,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333

    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[147] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
// \-                      { strcpy(yylval.tokens, yytext); printf("NEG %s\n", yytext); return NEG_T;}

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "y.tab.h"

#line 905 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 13 "lex.l"



#line 1127 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 334 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1219 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 16 "lex.l"
{ strcpy(yylval.tokens, yytext); return COMMENT_T;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 17 "lex.l"
{ strcpy(yylval.tokens, yytext); return GOTO_T;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 18 "lex.l"
{ strcpy(yylval.tokens, yytext); return BR_T;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 19 "lex.l"
{ strcpy(yylval.tokens, yytext); return NV_T;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 20 "lex.l"
{ strcpy(yylval.tokens, yytext); return PAGE_T;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 21 "lex.l"
{ strcpy(yylval.tokens, yytext); return NY_T;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 22 "lex.l"
{ strcpy(yylval.tokens, yytext); return ENY_T;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 23 "lex.l"
{ strcpy(yylval.tokens, yytext); return IM_T;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 24 "lex.l"
{ strcpy(yylval.tokens, yytext); return SB_T;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 25 "lex.l"
{ strcpy(yylval.tokens, yytext); return MS_T;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 26 "lex.l"
{ strcpy(yylval.tokens, yytext); return DH_T;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 27 "lex.l"
{ strcpy(yylval.tokens, yytext); return HS_T;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 28 "lex.l"
{ strcpy(yylval.tokens, yytext); return SE_T;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 29 "lex.l"
{ strcpy(yylval.tokens, yytext); return CS_T;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 30 "lex.l"
{ strcpy(yylval.tokens, yytext); return FE_T;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 31 "lex.l"
{ strcpy(yylval.tokens, yytext); return DC_T;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 32 "lex.l"
{ strcpy(yylval.tokens, yytext); return SX_T;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 33 "lex.l"
{ strcpy(yylval.tokens, yytext); return PL_T;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 34 "lex.l"
{ strcpy(yylval.tokens, yytext); return CO_T;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 35 "lex.l"
{ strcpy(yylval.tokens, yytext); return SD_T;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 36 "lex.l"
{ strcpy(yylval.tokens, yytext); return UC_T;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 37 "lex.l"
{ strcpy(yylval.tokens, yytext); return VI_T;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 38 "lex.l"
{ strcpy(yylval.tokens, yytext); return RF_T;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 39 "lex.l"
{ strcpy(yylval.tokens, yytext); return DS_T;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 40 "lex.l"
{ strcpy(yylval.tokens, yytext); return LI_T;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 41 "lex.l"
{ strcpy(yylval.tokens, yytext); return PN_T;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 42 "lex.l"
{ strcpy(yylval.tokens, yytext); return DU_T;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 43 "lex.l"
{ strcpy(yylval.tokens, yytext); return TI_T;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 44 "lex.l"
{ strcpy(yylval.tokens, yytext); return VS_T;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 45 "lex.l"
{ strcpy(yylval.tokens, yytext); return IN_T;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 46 "lex.l"
{ strcpy(yylval.tokens, yytext); return IR_T;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 47 "lex.l"
{ strcpy(yylval.tokens, yytext); return DA_T;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 48 "lex.l"
{ strcpy(yylval.tokens, yytext); return FO_T;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 49 "lex.l"
{ strcpy(yylval.tokens, yytext); return LL_T;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 50 "lex.l"
{ strcpy(yylval.tokens, yytext); return RH_T;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 51 "lex.l"
{ strcpy(yylval.tokens, yytext); return CT_T;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 52 "lex.l"
{ strcpy(yylval.tokens, yytext); return PA_T;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 53 "lex.l"
{ strcpy(yylval.tokens, yytext); return DR_T;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 54 "lex.l"
{ strcpy(yylval.tokens, yytext); return KP_T;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 55 "lex.l"
{ strcpy(yylval.tokens, yytext); return IF_T;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 56 "lex.l"
{ strcpy(yylval.tokens, yytext); return RI_T;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 57 "lex.l"
{ strcpy(yylval.tokens, yytext); return OI_T;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 58 "lex.l"
{ strcpy(yylval.tokens, yytext); return CB_T;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 59 "lex.l"
{ strcpy(yylval.tokens, yytext); return SC_T;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 60 "lex.l"
{ strcpy(yylval.tokens, yytext); return MC_T;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 61 "lex.l"
{ strcpy(yylval.tokens, yytext); return QU_T;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 62 "lex.l"
{ strcpy(yylval.tokens, yytext); return HW_T;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 63 "lex.l"
{ strcpy(yylval.tokens, yytext); return IL_T;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 64 "lex.l"
{ strcpy(yylval.tokens, yytext); return OC_T;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 65 "lex.l"
{ strcpy(yylval.tokens, yytext); return BC_T;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 66 "lex.l"
{ strcpy(yylval.tokens, yytext); return IS_T;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 67 "lex.l"
{ strcpy(yylval.tokens, yytext); return UP_T;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 68 "lex.l"
{ strcpy(yylval.tokens, yytext); return LS_T;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 69 "lex.l"
{ strcpy(yylval.tokens, yytext); return TU_T;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 70 "lex.l"
{ strcpy(yylval.tokens, yytext); return TR_T;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 71 "lex.l"
{ strcpy(yylval.tokens, yytext); return PW_T;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 72 "lex.l"
{ strcpy(yylval.tokens, yytext); return AF_T;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 73 "lex.l"
{ strcpy(yylval.tokens, yytext); return UD_T;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 74 "lex.l"
{ strcpy(yylval.tokens, yytext); return TL_T;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 75 "lex.l"
{ strcpy(yylval.tokens, yytext); return SS_T;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 76 "lex.l"
{ strcpy(yylval.tokens, yytext); return ON_T;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 77 "lex.l"
{ strcpy(yylval.tokens, yytext); return CC_T;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 78 "lex.l"
{ strcpy(yylval.tokens, yytext); return QQ_T;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 79 "lex.l"
{ strcpy(yylval.tokens, yytext); return RC_T;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 80 "lex.l"
{ strcpy(yylval.tokens, yytext); return NR_T;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 81 "lex.l"
{ strcpy(yylval.tokens, yytext); return BF_T;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 82 "lex.l"
{ strcpy(yylval.tokens, yytext); return IT_T;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 83 "lex.l"
{ strcpy(yylval.tokens, yytext); return UN_T;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 84 "lex.l"
{ strcpy(yylval.tokens, yytext); return AM_T;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 85 "lex.l"
{ strcpy(yylval.tokens, yytext); return JU_T;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 86 "lex.l"
{ strcpy(yylval.tokens, yytext); return EL_T;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 87 "lex.l"
{ strcpy(yylval.tokens, yytext); return TH_T;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 88 "lex.l"
{ strcpy(yylval.tokens, yytext); return OR_T;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 89 "lex.l"
{ strcpy(yylval.tokens, yytext); return CD_T;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 90 "lex.l"
{ strcpy(yylval.tokens, yytext); return TD_T;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 91 "lex.l"
{ strcpy(yylval.tokens, yytext); return SU_T;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 92 "lex.l"
{ strcpy(yylval.tokens, yytext); return DM_T;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 93 "lex.l"
{ strcpy(yylval.tokens, yytext); return GS_T;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 94 "lex.l"
{ strcpy(yylval.tokens, yytext); return TB_T;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 95 "lex.l"
{ strcpy(yylval.tokens, yytext); return SK_T;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 96 "lex.l"
{ strcpy(yylval.tokens, yytext); return CE_T;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 97 "lex.l"
{ strcpy(yylval.tokens, yytext); return CL_T;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 98 "lex.l"
{ strcpy(yylval.tokens, yytext); return AN_T;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 99 "lex.l"
{ strcpy(yylval.tokens, yytext); return OF_T;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 100 "lex.l"
{ strcpy(yylval.tokens, yytext); return HR_T;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 101 "lex.l"
{ strcpy(yylval.tokens, yytext); return VR_T;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 102 "lex.l"
{ strcpy(yylval.tokens, yytext); return HY_T;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 103 "lex.l"
{ strcpy(yylval.tokens, yytext); return OV_T;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 104 "lex.l"
{ strcpy(yylval.tokens, yytext); return ME_T;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 105 "lex.l"
{ strcpy(yylval.tokens, yytext); return UL_T;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 106 "lex.l"
{ strcpy(yylval.tokens, yytext); return DOTNY_T;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 107 "lex.l"
{ strcpy(yylval.tokens, yytext); return AT_T;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 108 "lex.l"
{ strcpy(yylval.tokens, yytext); return OG_T;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 109 "lex.l"
{ strcpy(yylval.tokens, yytext); return WEIGHT_T;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 110 "lex.l"
{ strcpy(yylval.tokens, yytext); return EXECUTE_T;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 111 "lex.l"
{ strcpy(yylval.tokens, yytext); return NOTEQUAL_T;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 112 "lex.l"
{ strcpy(yylval.tokens, yytext); return EQUAL_T;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 113 "lex.l"
{ strcpy(yylval.tokens, yytext); return GTHAN_T;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 114 "lex.l"
{ strcpy(yylval.tokens, yytext); return LTHAN_T;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 115 "lex.l"
{ strcpy(yylval.tokens, yytext); return GTHANE_T;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 116 "lex.l"
{ strcpy(yylval.tokens, yytext); return LTHANE_T;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 117 "lex.l"
{ strcpy(yylval.tokens, yytext); return UPPERCASE_T;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 118 "lex.l"
{ strcpy(yylval.tokens, yytext); return LENGTH_T;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 119 "lex.l"
{ strcpy(yylval.tokens, yytext); return AR_T;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 120 "lex.l"
{ strcpy(yylval.tokens, yytext); return BX_T;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 121 "lex.l"
{ strcpy(yylval.tokens, yytext); return SP_T;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 122 "lex.l"
{ strcpy(yylval.tokens, yytext); return SL_T;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 123 "lex.l"
{ strcpy(yylval.tokens, yytext); return US_T;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 124 "lex.l"
{ strcpy(yylval.tokens, yytext); return TM_T;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 125 "lex.l"
{ strcpy(yylval.tokens, yytext); return BM_T;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 126 "lex.l"
{ strcpy(yylval.tokens, yytext); return PM_T;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 127 "lex.l"
{ strcpy(yylval.tokens, yytext); return WIDTH_T;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 128 "lex.l"
{ strcpy(yylval.tokens, yytext); return TP_T;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 129 "lex.l"
{ strcpy(yylval.tokens, yytext); return TA_T;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 130 "lex.l"
{ strcpy(yylval.tokens, yytext); return ROTATE_T;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 131 "lex.l"
{ strcpy(yylval.tokens, yytext); return DEPTH_T;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 132 "lex.l"
{ strcpy(yylval.tokens, yytext); return SUBSTR_T;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 133 "lex.l"
{ strcpy(yylval.tokens, yytext); return MF_T;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 134 "lex.l"
{ strcpy(yylval.tokens, yytext); return UNKNOWN_T;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 135 "lex.l"
{ strcpy(yylval.tokens, yytext); return MG_T;}
	YY_BREAK
case 121:
#line 137 "lex.l"
case 122:
YY_RULE_SETUP
#line 137 "lex.l"
{ strcpy(yylval.tokens, yytext); return SIZE_T;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 138 "lex.l"
{ strcpy(yylval.tokens, yytext); return SIZE_T;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 139 "lex.l"
{ strcpy(yylval.tokens, yytext); return SIZE_T;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 140 "lex.l"
{ strcpy(yylval.tokens, yytext); return SIZE_T;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 141 "lex.l"
{ strcpy(yylval.tokens, yytext); return NEW_T;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 142 "lex.l"
{ strcpy(yylval.tokens, yytext); return SET_T;}
	YY_BREAK
case 128:
/* rule 128 can match eol */
YY_RULE_SETUP
#line 143 "lex.l"
{ strcpy(yylval.tokens, yytext); return NEW_LINE_T; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 144 "lex.l"
{ strcpy(yylval.tokens, yytext); return STYLE_T;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 145 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_UP_T;}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 146 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_T;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 147 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_T;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 148 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_T;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 149 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_T;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 150 "lex.l"
{ strcpy(yylval.tokens, yytext); return NUM_T;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 151 "lex.l"
{ strcpy(yylval.tokens, yytext); return NUM_T;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 152 "lex.l"
{ strcpy(yylval.tokens, yytext); return NUM_T;}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 153 "lex.l"
{ strcpy(yylval.tokens, yytext); return IDENT_T;}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 154 "lex.l"
{ strcpy(yylval.tokens, yytext); return LABEL_T;}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 155 "lex.l"
{ strcpy(yylval.tokens, yytext); return MATHEX_T;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 156 "lex.l"
{ strcpy(yylval.tokens, yytext); return IDENT_T;}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 157 "lex.l"
{ strcpy(yylval.tokens, yytext); return MATHEX_T;}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 158 "lex.l"
{ strcpy(yylval.tokens, yytext); return IDENT_T;}                  
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 159 "lex.l"
{ strcpy(yylval.tokens, yytext); return IDENT_T;}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 160 "lex.l"
;
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 161 "lex.l"
ECHO;
	YY_BREAK
#line 1922 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 334 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 334 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 333);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 161 "lex.l"




int yywrap(void){
    return 1;
}


    

