
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 150
#define YY_END_OF_BUFFER 151
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[345] =
    {   0,
        0,    0,  151,  150,  149,  130,    1,  144,  150,  144,
      144,  145,  143,  141,  138,  144,  148,  100,   98,   99,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,    0,  134,  134,  134,
      134,  134,    0,  144,    0,    0,  138,  144,  138,    0,
        2,  141,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  125,  144,  144,  144,  102,   97,  101,
      144,  104,  144,  144,  144,  144,  144,  144,    0,  147,

      144,  144,  144,  144,   97,  144,  144,  144,  144,  144,
        0,    0,  104,  103,  146,    0,  144,  133,    0,    0,
        0,    0,    0,  125,  137,  137,  137,    2,    2,  141,
      120,   58,   70,   84,  105,   93,   51,   67,  112,    4,
      106,   44,   63,   75,   82,   83,   20,   15,   37,   33,
       17,   12,   78,   39,   25,   28,   72,   98,   16,   34,
      101,    3,   79,   99,  109,   86,   13,   48,   88,   41,
       49,    9,   31,   32,   52,   68,   71,   40,  102,   26,
       35,   54,  100,   46,   90,  120,   11,   66,    5,   92,
       50,   85,   94,   43,   62,   74,   89,   38,   19,  113,

       27,   57,   64,   47,   65,   24,   36,   42,   10,   45,
       21,   14,   81,  108,  107,   61,   77,   18,  116,   80,
       76,   73,   29,   60,  111,  115,   56,   55,   22,   59,
       91,   69,   53,  110,   23,   87,   30,  120,   97,  140,
      139,  144,  144,  144,  126,  125,  131,  144,  144,  144,
      144,  128,  144,  129,  144,  144,  144,  135,  135,  135,
      135,  135,  144,  144,  144,  144,  144,  144,  144,  136,
      136,  136,  136,  136,    0,  133,  140,  139,    0,    0,
        0,  126,  125,  142,  141,  123,  123,  144,  144,  144,
      127,  144,  144,  144,  124,  126,  144,  144,    7,  144,

        6,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      114,  121,    0,    0,    0,  127,    0,    0,    0,  124,
      126,  127,  124,  144,    8,  118,  144,  114,  144,  144,
      144,  144,  144,  127,  124,  132,  144,   95,  144,  144,
      117,  119,   96,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    6,    7,    8,    9,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,   22,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,    9,   49,   49,   49,    1,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   75,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   76,   76,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   76,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   77,   77,   77,   49,    1,   78,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   77,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   77,   76,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[79] =
    {   0,
        1,    1,    2,    3,    1,    4,    5,    6,    4,    4,
        1,    4,    7,    7,    4,    7,    4,    1,    4,    3,
        4,    1,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    6,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    4,    3
    } ;

static yyconst flex_uint16_t yy_base[358] =
    {   0,
        0,    0,  637, 1211, 1211, 1211, 1211,    0,   72,   76,
        0,   70,   71,  137,   76,  192, 1211,   73, 1211,  614,
      606,  614,  594,  596,  588,   58,   84,  541,  558,  538,
      556,  542,   42,   44,   92,    0,  577,  586,  100,  102,
      106,  110,  577,  240,  108,  107,  238,  109,  241,   92,
      263,  568,  336,  408,  462,  513,  562,  245,  609,  645,
      692,  253,  263,  735,  780,  273,  824,  873,  255,  331,
      922,  973, 1019,  343,  271,  401, 1063,  510,  562,  338,
      538,  537,  505,  504,  379,  425,  464, 1211,    0, 1211,
      523,    0,  515,  522,  504,  509,  513,  481,  261, 1211,

        0,  474,  462,  471,  450,  452,  450,  461,  449,  453,
      326,  483, 1211, 1211, 1211,  490,  587,  822,  479,  421,
      459,  458,  430,  420,    0,  471,  469,    0,  920,  647,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  554,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  596,    0,  485,
      493,  441,  439,  410,  409,    0,  452,  113,  611,  604,
      426,    0,  439,    0,  435,  416,  384,    0,  443,  442,
      441,  439,  392,  375,  390,  384,  364,  375,  361,    0,
      418,  411,  400,  399,  397,  386,  517,  656,  346,  345,
      317,  313, 1211,  729,  773,    0,  622,  333,  332,  304,
      296,  308,  303,  274,  273,    0, 1109,  687,  316,  300,

        0,  297,  296,  258,  239,  234,  218,  217,  211,  221,
      220, 1211,  240,  236,  207,  199,  224,  221,  187,  184,
     1211,    0,    0,  116,  226,    0,  117,    0,  100,   86,
       94,   74,   71, 1211, 1211,    0,  120,    0,   71,   83,
        0,    0,    0, 1211, 1154, 1157, 1164,  124, 1171, 1175,
       97,   93, 1182, 1189, 1193, 1198, 1203
    } ;

static yyconst flex_int16_t yy_def[358] =
    {   0,
      344,    1,  344,  344,  344,  344,  344,  345,  346,  345,
      345,  344,  345,  344,  345,  345,  344,  345,  344,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  344,  346,  346,  346,
      346,  346,  344,  347,  344,  344,  344,  345,  345,  348,
      349,  345,  350,  350,   54,   54,   54,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,  345,  345,
      345,  345,  345,  345,   16,   16,   16,  344,  345,  344,
      345,  345,  345,  345,  345,  345,  345,  345,  351,  344,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      352,  344,  344,  344,  344,  353,  347,  347,  344,  344,
      344,  344,  344,  344,  348,  348,  348,  354,  349,  355,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  356,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  356,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,   16,   16,
      345,  345,  345,  345,  345,  345,  345,  351,  351,  351,
      351,  351,  345,  345,  345,  345,  345,  345,  345,  352,
      352,  352,  352,  352,  344,  353,  344,  344,  344,  344,
      344,  344,  344,  355,  355,  357,  356,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,   16,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  345,  345,  297,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  344,  344,  345,  345,  345,  345,  345,
      345,  345,  345,    0,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344
    } ;

static yyconst flex_uint16_t yy_nxt[1290] =
    {   0,
        4,    5,    6,    7,    4,    8,    9,   10,    8,   11,
       12,    8,   13,   14,   11,   15,   16,   17,   18,   19,
       20,    4,    8,    8,    8,   21,    8,    8,    8,    8,
        8,    8,    8,   22,    8,   23,    8,   24,    8,    8,
       25,    8,    8,    8,   26,   27,    8,    8,    8,    8,
        8,   28,   29,   30,    8,    8,    8,    8,    8,    8,
        8,    8,   31,    8,    8,    8,   32,   33,    8,    8,
        8,   34,   35,    8,    8,    8,    8,    4,   37,   43,
       45,   44,   46,   48,   96,   47,   49,   79,   97,   80,
       99,   49,   88,   89,  100,  107,  101,  109,  111,  270,

       81,  110,  100,  258,  101,   39,  344,  113,  344,  114,
       82,  108,  344,  113,   40,   98,  344,  114,   45,   46,
       46,   48,   47,   47,   49,  126,  247,   83,  248,  336,
      125,  337,   41,  336,  127,  337,  343,   84,  328,  338,
      342,   42,   36,   50,   36,   36,   51,  341,   36,   36,
       52,   36,   36,   36,  340,   36,  339,   36,  338,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   75,   75,   75,   75,   36,   53,   54,   55,   56,
       57,   76,   59,   60,   61,   62,   63,   64,   77,   78,

       67,   68,   69,   70,   71,   72,   73,   74,   75,   75,
       75,   75,   36,   36,   85,   85,   85,   85,   86,   85,
       85,   85,   85,   85,   85,   85,   85,   87,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
      116,  116,  297,  116,  116,  335,  116,  118,  335,  119,
      116,  120,   79,   47,   80,  335,   49,  116,  335,  116,
      334,  116,  121,  128,  128,   81,  128,  128,  334,  128,
      334,  159,  122,  128,  334,   82,  328,  333,  131,  332,
      128,  160,  128,  131,  128,  331,  131,  330,  131,  123,
      326,  131,   83,  203,  259,  177,  131,  204,  159,  124,

      178,  131,   84,  260,  131,  131,  131,  329,  160,  131,
      131,  131,  188,  131,  328,  131,  189,  116,  131,  190,
      203,  261,  177,  131,  204,  328,  327,  178,  131,  326,
      262,  131,  297,  131,  323,  323,  131,  323,  131,  188,
      128,   36,  323,   36,   36,   36,  190,   36,   36,   36,
       36,   36,   36,  241,   36,  205,   36,  322,  206,  271,
      207,  208,  242,  132,  131,  322,  322,  322,  272,  131,
      133,  134,  243,  235,  321,  135,  131,  136,  321,  321,
      321,  131,  236,  237,   36,  206,  273,  207,  208,  244,
      132,  131,  247,  276,  248,  274,  131,  133,  134,  245,

      235,  312,  135,  131,  136,   85,  114,  113,  131,  236,
      237,   36,   36,   36,   85,   36,   36,   36,  114,   36,
       36,   36,   36,   36,   36,  113,   36,  159,   36,  311,
      310,  309,  137,  308,  131,  138,  278,  160,  247,  131,
      248,  307,  139,  306,  305,  279,  114,  140,  113,  114,
      113,   85,  304,  141,  159,  280,   36,  303,  170,  137,
      249,  131,  138,  302,  160,  301,  131,  300,  297,  139,
      296,  296,  281,  296,  140,  296,  114,  247,  113,  248,
      141,  283,  282,   36,   36,  142,  143,  144,  145,  131,
       85,  283,  283,  283,  277,  146,  131,  276,  147,   85,

      240,  131,  148,  149,  275,  269,  268,  131,  241,  288,
      250,  267,  142,  143,  144,  145,  131,  292,  254,  289,
      266,  252,  146,  131,  265,  147,  264,  293,  131,  148,
      149,  263,  277,  257,  131,  150,  290,  151,  256,  255,
      131,  313,  152,  131,  294,  254,  291,  153,  131,  188,
      253,  314,  154,  155,  295,  156,  190,  286,  131,  252,
      251,   36,  150,  239,  151,  246,  246,  131,  315,  152,
      131,  246,  246,  286,  153,  131,  188,  240,  316,  154,
      155,  130,  156,  190,  115,  131,  131,  116,  116,  131,
      116,  116,  344,  116,  118,  157,  131,  116,  112,  286,

      158,  131,   36,   36,  116,  106,  116,  131,  116,  105,
      104,  103,  102,  131,   95,  286,  131,  299,   94,  248,
       93,   92,  157,  131,  247,  286,  248,  158,  131,   36,
       85,  286,   91,   90,  131,  161,  344,   85,  344,   85,
      344,  286,  131,  344,   36,  162,   85,  131,  344,  163,
      164,  344,   36,  344,   36,   36,   36,  298,   36,  344,
      285,   36,  161,   36,  116,   36,  344,   36,  344,  131,
       36,  278,  162,  286,  131,  344,  163,  164,  131,  165,
      317,  344,  344,  131,  166,  167,  344,  344,  344,  168,
      318,  169,  344,  344,  344,   36,  344,  344,  344,  286,

      325,  344,  248,  344,  344,  131,  165,  319,  344,  344,
      131,  166,  167,   85,  344,  344,  168,  320,  169,  170,
      344,  344,   85,  344,  344,  171,  172,  173,  344,  344,
      131,  174,  175,  176,   36,  344,   36,   36,   36,  344,
       36,  344,  344,   36,  344,   36,  170,   36,  344,   36,
      344,  344,  171,  172,  173,  344,  344,  131,  174,  175,
      176,  179,  344,  344,  344,  180,  344,  344,  181,  344,
      344,  344,  344,  131,  344,  182,  183,   36,   36,  344,
       36,   36,   36,  344,   36,  344,  285,   36,  179,   36,
      344,   36,  180,   36,  344,  181,  344,  344,  344,  344,

      131,  344,  182,  183,  184,  344,  185,  344,  186,  344,
      344,  344,  344,  131,  344,  344,  344,  344,  131,  344,
      187,   36,  116,  116,  344,  116,  116,  344,  116,  118,
      344,  184,  116,  185,  344,  186,  344,  344,  344,  116,
      131,  116,  344,  116,  344,  131,  344,  187,  191,  344,
      344,  192,  193,  344,  194,  344,  344,  131,  344,  195,
      344,  344,  131,  196,  344,  344,  344,  197,  344,  344,
      344,  344,  344,  344,  344,  191,  344,  344,  192,  193,
      344,  194,  344,  344,  131,  344,  195,  344,  344,  131,
      196,  344,  344,  344,  197,  198,  344,  344,  344,  116,

      344,  344,  344,  344,  344,  344,  199,  200,  201,  344,
      344,  131,  344,  344,  344,  344,  344,  202,  344,  344,
      128,  128,  198,  128,  128,  344,  128,  344,  344,  344,
      128,  344,  344,  199,  200,  201,  344,  128,  131,  128,
      344,  128,  344,  344,  202,  209,  210,  211,  212,  344,
      344,  344,  344,  344,  213,  214,  344,  344,  344,  215,
      131,  344,  216,  344,  217,  344,  344,  218,  344,  344,
      344,  344,  209,  210,  211,  212,  344,  344,  344,  344,
      344,  213,  214,  344,  344,  344,  215,  131,  344,  216,
      344,  217,  344,  344,  218,  219,  220,  128,  221,  344,

      344,  344,  222,  223,  344,  344,  224,  225,  344,  344,
      226,  131,  227,  344,  344,  228,  344,  344,  344,  344,
      344,  344,  219,  220,  344,  221,  344,  344,  344,  222,
      223,  344,  344,  224,  225,  344,  344,  226,  131,  227,
      344,  344,  228,  229,  230,  344,  344,  344,  344,  344,
      344,  344,  231,  344,  232,  344,  233,  131,  344,  234,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      229,  230,  344,  344,  344,  344,  344,  344,  344,  231,
      344,  232,  344,  233,  131,  344,  234,  184,  344,  185,
      344,  186,  344,  344,  344,  344,  131,  344,  344,  344,

      344,  131,  344,  187,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  184,  344,  185,  344,  238,  344,
      344,  344,  344,  131,  344,  344,  344,  344,  131,  344,
      187,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,   36,  344,   36,
       36,   38,  344,   38,  117,  344,  117,  117,  117,  117,
      117,  129,  344,  129,  129,  129,  129,  129,  131,  344,
      131,  131,  116,  344,  116,  116,  116,  116,  116,  128,
      344,  128,  128,  128,  128,  128,  284,  344,  284,  284,

      287,  287,  344,  287,  287,  286,  286,  344,  344,  286,
        3,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344
    } ;

static yyconst flex_int16_t yy_chk[1290] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   10,
       12,   10,   12,   13,   26,   12,   13,   15,   26,   15,
       27,   15,   18,   18,   27,   33,   27,   34,   35,  352,

       15,   34,   35,  351,   35,    9,   39,   39,   40,   40,
       15,   33,   41,   41,    9,   26,   42,   42,   45,   46,
       45,   48,   46,   45,   48,   50,  248,   15,  248,  324,
      348,  324,    9,  337,   50,  337,  340,   15,  339,  333,
      332,    9,   14,   14,   14,   14,   14,  331,   14,   14,
       14,   14,   14,   14,  330,   14,  329,   14,  327,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,

       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       44,   44,  325,   44,   44,  320,   44,   44,  319,   47,
       44,   47,   49,   47,   49,  318,   49,   44,  317,   44,
      316,   44,   47,   51,   51,   49,   51,   51,  315,   51,
      314,   58,   47,   51,  313,   49,  311,  310,   58,  309,
       51,   58,   51,   58,   51,  308,   62,  307,   69,   47,
      306,   62,   49,   69,   99,   62,   63,   69,   58,   47,

       63,   63,   49,   99,   75,   58,   66,  305,   58,   75,
       58,   66,   66,   62,  304,   69,   66,   44,   62,   66,
       69,   99,   62,   63,   69,  303,  302,   63,   63,  300,
       99,   75,  299,   66,  295,  294,   75,  293,   66,   66,
       51,   53,  292,   53,   53,   53,   66,   53,   53,   53,
       53,   53,   53,   80,   53,   70,   53,  291,   70,  111,
       70,   70,   80,   53,   70,  290,  289,  288,  111,   70,
       53,   53,   80,   74,  282,   53,   74,   53,  281,  280,
      279,   74,   74,   74,   53,   70,  111,   70,   70,   80,
       53,   70,   85,  276,   85,  111,   70,   53,   53,   80,

       74,  275,   53,   74,   53,   85,  274,  273,   74,   74,
       74,   53,   53,   54,   85,   54,   54,   54,  272,   54,
       54,   54,   54,   54,   54,  271,   54,   76,   54,  269,
      268,  267,   54,  266,   76,   54,  120,   76,   86,   76,
       86,  265,   54,  264,  263,  120,  262,   54,  261,  260,
      259,   86,  257,   54,   76,  120,   54,  256,   76,   54,
       86,   76,   54,  255,   76,  253,   76,  251,  247,   54,
      245,  244,  120,  243,   54,  242,  127,   87,  126,   87,
       54,  124,  120,   54,   54,   55,   55,   55,   55,   55,
       87,  123,  122,  121,  119,   55,   55,  116,   55,   87,

      240,   55,   55,   55,  112,  110,  109,   55,  241,  240,
       87,  108,   55,   55,   55,   55,   55,  241,  107,  240,
      106,  105,   55,   55,  104,   55,  103,  241,   55,   55,
       55,  102,  277,   98,   55,   56,  240,   56,   97,   96,
       56,  277,   56,   78,  241,   95,  240,   56,   78,   78,
       94,  277,   56,   56,  241,   56,   78,  186,   56,   93,
       91,  186,   56,   78,   56,   84,   83,   56,  277,   56,
       78,   82,   81,  186,   56,   78,   78,   79,  277,   56,
       56,   52,   56,   78,   43,   56,   57,  117,  117,   57,
      117,  117,   38,  117,  117,   57,   57,  117,   37,  238,

       57,   57,  186,  238,  117,   32,  117,   57,  117,   31,
       30,   29,   28,   57,   25,  238,   57,  250,   24,  250,
       23,   22,   57,   57,  249,  287,  249,   57,   57,  287,
      250,  186,   21,   20,   57,   59,    3,  249,    0,  250,
        0,  287,   59,    0,  238,   59,  249,   59,    0,   59,
       59,    0,  130,    0,  130,  130,  130,  249,  130,    0,
      130,  130,   59,  130,  117,  130,    0,  130,    0,   59,
      287,  278,   59,  238,   59,    0,   59,   59,   60,   60,
      278,    0,    0,   60,   60,   60,    0,    0,    0,   60,
      278,   60,    0,    0,    0,  130,    0,    0,    0,  287,

      298,    0,  298,    0,    0,   60,   60,  278,    0,    0,
       60,   60,   60,  298,    0,    0,   60,  278,   60,   61,
        0,    0,  298,    0,    0,   61,   61,   61,    0,    0,
       61,   61,   61,   61,  284,    0,  284,  284,  284,    0,
      284,    0,    0,  284,    0,  284,   61,  284,    0,  284,
        0,    0,   61,   61,   61,    0,    0,   61,   61,   61,
       61,   64,    0,    0,    0,   64,    0,    0,   64,    0,
        0,    0,    0,   64,    0,   64,   64,  284,  285,    0,
      285,  285,  285,    0,  285,    0,  285,  285,   64,  285,
        0,  285,   64,  285,    0,   64,    0,    0,    0,    0,

       64,    0,   64,   64,   65,    0,   65,    0,   65,    0,
        0,    0,    0,   65,    0,    0,    0,    0,   65,    0,
       65,  285,  118,  118,    0,  118,  118,    0,  118,  118,
        0,   65,  118,   65,    0,   65,    0,    0,    0,  118,
       65,  118,    0,  118,    0,   65,    0,   65,   67,    0,
        0,   67,   67,    0,   67,    0,    0,   67,    0,   67,
        0,    0,   67,   67,    0,    0,    0,   67,    0,    0,
        0,    0,    0,    0,    0,   67,    0,    0,   67,   67,
        0,   67,    0,    0,   67,    0,   67,    0,    0,   67,
       67,    0,    0,    0,   67,   68,    0,    0,    0,  118,

        0,    0,    0,    0,    0,    0,   68,   68,   68,    0,
        0,   68,    0,    0,    0,    0,    0,   68,    0,    0,
      129,  129,   68,  129,  129,    0,  129,    0,    0,    0,
      129,    0,    0,   68,   68,   68,    0,  129,   68,  129,
        0,  129,    0,    0,   68,   71,   71,   71,   71,    0,
        0,    0,    0,    0,   71,   71,    0,    0,    0,   71,
       71,    0,   71,    0,   71,    0,    0,   71,    0,    0,
        0,    0,   71,   71,   71,   71,    0,    0,    0,    0,
        0,   71,   71,    0,    0,    0,   71,   71,    0,   71,
        0,   71,    0,    0,   71,   72,   72,  129,   72,    0,

        0,    0,   72,   72,    0,    0,   72,   72,    0,    0,
       72,   72,   72,    0,    0,   72,    0,    0,    0,    0,
        0,    0,   72,   72,    0,   72,    0,    0,    0,   72,
       72,    0,    0,   72,   72,    0,    0,   72,   72,   72,
        0,    0,   72,   73,   73,    0,    0,    0,    0,    0,
        0,    0,   73,    0,   73,    0,   73,   73,    0,   73,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       73,   73,    0,    0,    0,    0,    0,    0,    0,   73,
        0,   73,    0,   73,   73,    0,   73,   77,    0,   77,
        0,   77,    0,    0,    0,    0,   77,    0,    0,    0,

        0,   77,    0,   77,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   77,    0,   77,    0,   77,    0,
        0,    0,    0,   77,    0,    0,    0,    0,   77,    0,
       77,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  345,    0,  345,
      345,  346,    0,  346,  347,    0,  347,  347,  347,  347,
      347,  349,    0,  349,  349,  349,  349,  349,  350,    0,
      350,  350,  353,    0,  353,  353,  353,  353,  353,  354,
        0,  354,  354,  354,  354,  354,  355,    0,  355,  355,

      356,  356,    0,  356,  356,  357,  357,    0,    0,  357,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[151] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
// \-                      { strcpy(yylval.tokens, yytext); printf("NEG %s\n", yytext); return NEG_T;}

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "y.tab.h"

#line 904 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 13 "lex.l"


#line 1125 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 345 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1211 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 15 "lex.l"
{ strcpy(yylval.tokens, yytext); return SPACE_T;}               
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "lex.l"
{ strcpy(yylval.tokens, yytext); return COMMENT_T;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "lex.l"
{ strcpy(yylval.tokens, yytext); return GOTO_T;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "lex.l"
{ strcpy(yylval.tokens, yytext); return BR_T;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 19 "lex.l"
{ strcpy(yylval.tokens, yytext); return NV_T;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 "lex.l"
{ strcpy(yylval.tokens, yytext); return PAGE_T;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 21 "lex.l"
{ strcpy(yylval.tokens, yytext); return NY_T;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 22 "lex.l"
{ strcpy(yylval.tokens, yytext); return ENY_T;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 "lex.l"
{ strcpy(yylval.tokens, yytext); return IM_T;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 24 "lex.l"
{ strcpy(yylval.tokens, yytext); return SB_T;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 25 "lex.l"
{ strcpy(yylval.tokens, yytext); return MS_T;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 "lex.l"
{ strcpy(yylval.tokens, yytext); return DH_T;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 "lex.l"
{ strcpy(yylval.tokens, yytext); return HS_T;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 28 "lex.l"
{ strcpy(yylval.tokens, yytext); return SE_T;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 29 "lex.l"
{ strcpy(yylval.tokens, yytext); return CS_T;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 30 "lex.l"
{ strcpy(yylval.tokens, yytext); return FE_T;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 31 "lex.l"
{ strcpy(yylval.tokens, yytext); return DC_T;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 32 "lex.l"
{ strcpy(yylval.tokens, yytext); return SX_T;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 33 "lex.l"
{ strcpy(yylval.tokens, yytext); return PL_T;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 34 "lex.l"
{ strcpy(yylval.tokens, yytext); return CO_T;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 35 "lex.l"
{ strcpy(yylval.tokens, yytext); return SD_T;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 36 "lex.l"
{ strcpy(yylval.tokens, yytext); return UC_T;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 37 "lex.l"
{ strcpy(yylval.tokens, yytext); return VI_T;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 38 "lex.l"
{ strcpy(yylval.tokens, yytext); return RF_T;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 39 "lex.l"
{ strcpy(yylval.tokens, yytext); return DS_T;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 40 "lex.l"
{ strcpy(yylval.tokens, yytext); return LI_T;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 41 "lex.l"
{ strcpy(yylval.tokens, yytext); return PN_T;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 42 "lex.l"
{ strcpy(yylval.tokens, yytext); return DU_T;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 "lex.l"
{ strcpy(yylval.tokens, yytext); return TI_T;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 "lex.l"
{ strcpy(yylval.tokens, yytext); return VS_T;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 45 "lex.l"
{ strcpy(yylval.tokens, yytext); return IN_T;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 46 "lex.l"
{ strcpy(yylval.tokens, yytext); return IR_T;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 47 "lex.l"
{ strcpy(yylval.tokens, yytext); return DA_T;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 48 "lex.l"
{ strcpy(yylval.tokens, yytext); return FO_T;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 49 "lex.l"
{ strcpy(yylval.tokens, yytext); return LL_T;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 50 "lex.l"
{ strcpy(yylval.tokens, yytext); return RH_T;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 51 "lex.l"
{ strcpy(yylval.tokens, yytext); return CT_T;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 52 "lex.l"
{ strcpy(yylval.tokens, yytext); return PA_T;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 53 "lex.l"
{ strcpy(yylval.tokens, yytext); return DR_T;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 54 "lex.l"
{ strcpy(yylval.tokens, yytext); return KP_T;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 55 "lex.l"
{ strcpy(yylval.tokens, yytext); return IF_T;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 56 "lex.l"
{ strcpy(yylval.tokens, yytext); return RI_T;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 57 "lex.l"
{ strcpy(yylval.tokens, yytext); return OI_T;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 58 "lex.l"
{ strcpy(yylval.tokens, yytext); return CB_T;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 59 "lex.l"
{ strcpy(yylval.tokens, yytext); return SC_T;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 60 "lex.l"
{ strcpy(yylval.tokens, yytext); return MC_T;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 61 "lex.l"
{ strcpy(yylval.tokens, yytext); return QU_T;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 62 "lex.l"
{ strcpy(yylval.tokens, yytext); return HW_T;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 63 "lex.l"
{ strcpy(yylval.tokens, yytext); return IL_T;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 64 "lex.l"
{ strcpy(yylval.tokens, yytext); return OC_T;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 65 "lex.l"
{ strcpy(yylval.tokens, yytext); return BC_T;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 66 "lex.l"
{ strcpy(yylval.tokens, yytext); return IS_T;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 67 "lex.l"
{ strcpy(yylval.tokens, yytext); return UP_T;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 68 "lex.l"
{ strcpy(yylval.tokens, yytext); return LS_T;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 69 "lex.l"
{ strcpy(yylval.tokens, yytext); return TU_T;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 70 "lex.l"
{ strcpy(yylval.tokens, yytext); return TR_T;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 71 "lex.l"
{ strcpy(yylval.tokens, yytext); return PW_T;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 72 "lex.l"
{ strcpy(yylval.tokens, yytext); return AF_T;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 73 "lex.l"
{ strcpy(yylval.tokens, yytext); return UD_T;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 74 "lex.l"
{ strcpy(yylval.tokens, yytext); return TL_T;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 75 "lex.l"
{ strcpy(yylval.tokens, yytext); return SS_T;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 76 "lex.l"
{ strcpy(yylval.tokens, yytext); return ON_T;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 77 "lex.l"
{ strcpy(yylval.tokens, yytext); return CC_T;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 78 "lex.l"
{ strcpy(yylval.tokens, yytext); return QQ_T;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 79 "lex.l"
{ strcpy(yylval.tokens, yytext); return RC_T;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 80 "lex.l"
{ strcpy(yylval.tokens, yytext); return NR_T;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 81 "lex.l"
{ strcpy(yylval.tokens, yytext); return BF_T;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 82 "lex.l"
{ strcpy(yylval.tokens, yytext); return IT_T;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 83 "lex.l"
{ strcpy(yylval.tokens, yytext); return UN_T;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 84 "lex.l"
{ strcpy(yylval.tokens, yytext); return AM_T;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 85 "lex.l"
{ strcpy(yylval.tokens, yytext); return JU_T;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 86 "lex.l"
{ strcpy(yylval.tokens, yytext); return EL_T;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 87 "lex.l"
{ strcpy(yylval.tokens, yytext); return TH_T;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 88 "lex.l"
{ strcpy(yylval.tokens, yytext); return OR_T;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 89 "lex.l"
{ strcpy(yylval.tokens, yytext); return CD_T;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 90 "lex.l"
{ strcpy(yylval.tokens, yytext); return TD_T;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 91 "lex.l"
{ strcpy(yylval.tokens, yytext); return SU_T;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 92 "lex.l"
{ strcpy(yylval.tokens, yytext); return DM_T;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 93 "lex.l"
{ strcpy(yylval.tokens, yytext); return GS_T;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 94 "lex.l"
{ strcpy(yylval.tokens, yytext); return TB_T;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 95 "lex.l"
{ strcpy(yylval.tokens, yytext); return SK_T;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 96 "lex.l"
{ strcpy(yylval.tokens, yytext); return CE_T;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 97 "lex.l"
{ strcpy(yylval.tokens, yytext); return CL_T;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 98 "lex.l"
{ strcpy(yylval.tokens, yytext); return AN_T;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 99 "lex.l"
{ strcpy(yylval.tokens, yytext); return OF_T;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 100 "lex.l"
{ strcpy(yylval.tokens, yytext); return HR_T;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 101 "lex.l"
{ strcpy(yylval.tokens, yytext); return VR_T;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 102 "lex.l"
{ strcpy(yylval.tokens, yytext); return HY_T;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 103 "lex.l"
{ strcpy(yylval.tokens, yytext); return OV_T;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 104 "lex.l"
{ strcpy(yylval.tokens, yytext); return ME_T;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 105 "lex.l"
{ strcpy(yylval.tokens, yytext); return UL_T;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 106 "lex.l"
{ strcpy(yylval.tokens, yytext); return DOTNY_T;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 107 "lex.l"
{ strcpy(yylval.tokens, yytext); return AT_T;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 108 "lex.l"
{ strcpy(yylval.tokens, yytext); return OG_T;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 109 "lex.l"
{ strcpy(yylval.tokens, yytext); return WEIGHT_T;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 110 "lex.l"
{ strcpy(yylval.tokens, yytext); return EXECUTE_T;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 111 "lex.l"
{ strcpy(yylval.tokens, yytext); return NOTEQUAL_T;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 112 "lex.l"
{ strcpy(yylval.tokens, yytext); return EQUAL_T;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 113 "lex.l"
{ strcpy(yylval.tokens, yytext); return GTHAN_T;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 114 "lex.l"
{ strcpy(yylval.tokens, yytext); return LTHAN_T;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 115 "lex.l"
{ strcpy(yylval.tokens, yytext); return GTHANE_T;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 116 "lex.l"
{ strcpy(yylval.tokens, yytext); return LTHANE_T;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 117 "lex.l"
{ strcpy(yylval.tokens, yytext); return UPPERCASE_T;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 118 "lex.l"
{ strcpy(yylval.tokens, yytext); return LENGTH_T;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 119 "lex.l"
{ strcpy(yylval.tokens, yytext); return AR_T;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 120 "lex.l"
{ strcpy(yylval.tokens, yytext); return BX_T;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 121 "lex.l"
{ strcpy(yylval.tokens, yytext); return SP_T;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 122 "lex.l"
{ strcpy(yylval.tokens, yytext); return SL_T;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 123 "lex.l"
{ strcpy(yylval.tokens, yytext); return HM_T;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 124 "lex.l"
{ strcpy(yylval.tokens, yytext); return US_T;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 125 "lex.l"
{ strcpy(yylval.tokens, yytext); return TM_T;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 126 "lex.l"
{ strcpy(yylval.tokens, yytext); return BM_T;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 127 "lex.l"
{ strcpy(yylval.tokens, yytext); return PM_T;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 128 "lex.l"
{ strcpy(yylval.tokens, yytext); return WIDTH_T;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 129 "lex.l"
{ strcpy(yylval.tokens, yytext); return TP_T;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 130 "lex.l"
{ strcpy(yylval.tokens, yytext); return TA_T;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 131 "lex.l"
{ strcpy(yylval.tokens, yytext); return ROTATE_T;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 132 "lex.l"
{ strcpy(yylval.tokens, yytext); return DEPTH_T;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 133 "lex.l"
{ strcpy(yylval.tokens, yytext); return SUBSTR_T;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 134 "lex.l"
{ strcpy(yylval.tokens, yytext); return MF_T;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 135 "lex.l"
{ strcpy(yylval.tokens, yytext); return UNKNOWN_T;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 136 "lex.l"
{ strcpy(yylval.tokens, yytext); return MG_T;}
	YY_BREAK
case 123:
#line 138 "lex.l"
case 124:
YY_RULE_SETUP
#line 138 "lex.l"
{ strcpy(yylval.tokens, yytext); return SIZE_T;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 139 "lex.l"
{ strcpy(yylval.tokens, yytext); return SIZE_T;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 140 "lex.l"
{ strcpy(yylval.tokens, yytext); return SIZE_T;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 141 "lex.l"
{ strcpy(yylval.tokens, yytext); return SIZE_T;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 142 "lex.l"
{ strcpy(yylval.tokens, yytext); return NEW_T;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 143 "lex.l"
{ strcpy(yylval.tokens, yytext); return SET_T;}
	YY_BREAK
case 130:
/* rule 130 can match eol */
YY_RULE_SETUP
#line 144 "lex.l"
{ strcpy(yylval.tokens, yytext); return NEW_LINE_T; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 145 "lex.l"
{ strcpy(yylval.tokens, yytext); return STYLE_T;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 146 "lex.l"
{ strcpy(yylval.tokens, yytext); return STYLE_T;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 147 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_UP_T;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 148 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_T;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 149 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_T;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 150 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_T;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 151 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_T;}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 152 "lex.l"
{ strcpy(yylval.tokens, yytext); return NUM_T;}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 153 "lex.l"
{ strcpy(yylval.tokens, yytext); return NUM_T;}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 154 "lex.l"
{ strcpy(yylval.tokens, yytext); return NUM_T;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 155 "lex.l"
{ strcpy(yylval.tokens, yytext); return IDENT_T;}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 156 "lex.l"
{ strcpy(yylval.tokens, yytext); return LABEL_T;}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 157 "lex.l"
{ strcpy(yylval.tokens, yytext); return MATHEX_T;}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 158 "lex.l"
{ strcpy(yylval.tokens, yytext); return IDENT_T;}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 159 "lex.l"
{ strcpy(yylval.tokens, yytext); return MATHEX_T;}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 160 "lex.l"
{ strcpy(yylval.tokens, yytext); return IDENT_T;}                  
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 161 "lex.l"
{ strcpy(yylval.tokens, yytext); return IDENT_T;}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 162 "lex.l"
{ strcpy(yylval.tokens, yytext); return SEMICOLON_T;}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 163 "lex.l"
;
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 164 "lex.l"
ECHO;
	YY_BREAK
#line 1940 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 345 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 345 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 344);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 164 "lex.l"




int yywrap(void){
    return 1;
}


    

