
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[306] =
    {   0,
        0,    0,  103,  102,  101,   84,   97,  102,   97,   97,
       98,   96,   94,   91,   97,   57,   55,   56,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,    0,   87,   87,
       87,   87,   87,    0,   97,    0,    0,   91,   97,   91,
        0,    6,   94,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   81,

       97,   97,   97,   59,   54,   58,   55,   58,   56,   62,
       59,   57,   97,   12,   97,   97,   97,   97,    0,  100,
       97,   97,   97,   97,   97,   97,   97,   97,   97,    0,
        0,   62,   61,   99,    0,   97,   86,    0,    0,    0,
        0,    0,   81,   90,   90,   90,    6,    6,   94,   77,
       49,   63,   32,   69,    1,   64,   25,   40,   47,   48,
       16,   10,   43,   18,   37,   11,   13,   44,   51,   29,
       53,   22,   30,    8,    9,   33,   20,   14,   35,   27,
        2,   31,   50,   24,   39,   17,   70,   28,   15,   23,
       26,   66,   46,   65,   42,   73,   45,   41,   38,    7,

       68,   72,   36,   34,   67,   52,   77,   93,   92,   97,
       97,   97,   82,   81,   85,   97,   97,   97,   60,   97,
       97,   97,   97,   88,   88,   88,   88,   88,   97,   97,
       97,   97,   97,   97,   97,   89,   89,   89,   89,   89,
        0,   86,   93,   92,    0,    0,    0,   82,   81,   95,
       94,   79,   79,   97,   97,   97,   83,   97,   97,   97,
       80,   82,   97,    4,    3,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   71,   78,    0,    0,    0,   83,
        0,    0,    0,   80,   82,   83,   80,    5,   97,   71,
       97,   75,   97,   97,   97,   97,   83,   80,   19,   97,

       97,   74,   76,   21,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    6,    7,    8,    9,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,    1,   18,
       19,   20,   21,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   31,
       47,    9,   47,   47,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
       72,   57,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   73,   73,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   73,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   74,   74,   74,    1,    1,   75,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   74,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   74,   73,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    2,    3,    1,    4,    5,    6,    4,    4,
        1,    4,    7,    7,    4,    7,    4,    4,    3,    4,
        1,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    6,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    4,    3
    } ;

static yyconst flex_uint16_t yy_base[319] =
    {   0,
        0,    0,  619, 1052, 1052, 1052,    0,   69,   73,    0,
       67,   68,  132,   73,  185,   71, 1052,  597,  575,   60,
       74,   61,  585,   68,   92,  531,  541,   42,   41,   43,
      538,   51,  527,  516,   62,  109,    0,  561,  574,  118,
      122,  124,  127,  570,  231,  230,  221,  233,  235,  242,
       94,  258,  560,  328,  397,  262,  260,  280,  315,  332,
      346,  448,  349,  350,  395,  398,  415,  429,  428,  452,
      466,  489,  518,  522,  485,  530,  287,  553,  549,  572,
      576,  584,  603,  652,  606,  615,  633,  669,  656,  696,
      697,  742,  719,  738,  555,  762,  532,  531,  498,  491,

      254,  343,  492, 1052,    0, 1052,    0,    0,    0,    0,
        0,    0,  523,    0,  521,  515,  512,  485,  222, 1052,
        0,  477,  469,  477,  472,  450,  463,  454,  453,  511,
      482, 1052, 1052, 1052,  491,  812,  833,  476,  805,  455,
      450,  420,  417,    0,  461,  458,    0,  855,  863,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,  720,  808,  829,  430,
      423,  395,  391,    0,    0,  103,  724,  792,    0,  420,
      413,  397,  366,    0,  422,  419,  418,  417,  373,  356,
      370,  370,  342,  350,  331,    0,  389,  385,  378,  373,
      374,  368,  866,  868,  330,  328,  301,  295, 1052,  889,
      905,    0,  923,  319,  316,  275,  271,  295,  294,  267,
      264,    0,  835,    0,    0,  294,  293,  265,  251,  262,
      248,  248,  242,  253,  245, 1052,  264,  263,  231,  218,
      241,  240,  213,  212, 1052,    0,    0,    0,  230,    0,
      206,    0,  186,  192,  175,   86, 1052, 1052,    0,   85,

       91,    0,    0,    0, 1052,  995,  998, 1005,  114, 1012,
     1016,  102,   85, 1023, 1030, 1034, 1039, 1044
    } ;

static yyconst flex_int16_t yy_def[319] =
    {   0,
      305,    1,  305,  305,  305,  305,  306,  307,  306,  306,
      305,  306,  305,  306,  306,  306,  305,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  305,  307,  307,
      307,  307,  307,  305,  308,  305,  305,  305,  306,  306,
      309,  310,  306,  311,  311,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,  306,  306,  306,  306,  306,  306,

       15,   15,   15,  305,  306,  305,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  312,  305,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  313,
      305,  305,  305,  305,  314,  308,  308,  305,  305,  305,
      305,  305,  305,  309,  309,  309,  315,  310,  316,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,

      306,  306,  306,  306,  306,  306,  317,  306,  306,  306,
      306,  306,  306,  306,  306,  306,   15,   15,  306,  306,
      306,  306,  306,  312,  312,  312,  312,  312,  306,  306,
      306,  306,  306,  306,  306,  313,  313,  313,  313,  313,
      305,  314,  305,  305,  305,  305,  305,  305,  305,  316,
      316,  318,  317,  306,  306,  306,  306,  306,  306,  306,
      306,  306,   15,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  305,  305,  306,  306,

      306,  306,  306,  306,    0,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305
    } ;

static yyconst flex_uint16_t yy_nxt[1128] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,    7,   10,
       11,    7,   12,   13,   10,   14,   15,   16,   17,   18,
        4,    7,    7,    7,    7,   19,    7,   20,    7,    7,
        7,    7,   21,    7,    7,   22,   23,    7,    7,    7,
        7,    7,    7,   24,   25,    7,    7,    7,    7,   26,
       27,   28,    7,   29,    7,    7,    7,    7,   30,    7,
       31,   32,    7,    7,   33,   34,    7,    7,    7,   35,
       36,    7,    7,    7,    4,   38,   44,   46,   45,   47,
       49,  110,   48,   50,   95,  108,   96,  113,   50,  104,
      105,  236,  108,  116,  111,  114,   97,  117,  119,  111,

      109,   40,  120,  125,  121,  107,   98,  109,  224,  112,
       41,  114,  124,  128,  112,  130,  215,  129,  216,  120,
      144,  121,   99,  118,  305,  132,  145,   42,  305,  133,
      305,  132,  100,  305,  133,  146,   43,   37,   51,   37,
       37,   52,  304,   37,   37,   53,   37,   37,   37,   37,
      290,   37,  299,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   63,   63,   63,   37,   76,
       77,   78,   79,   80,   81,   82,   83,   84,   63,   85,
       86,   87,   63,   88,   89,   70,   90,   91,   92,   93,

       94,   63,   63,   63,   37,   37,  101,  101,  101,  101,
      102,  101,  101,  101,  101,  101,  101,  101,  101,  103,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  135,  135,   47,  135,  135,   48,  135,  137,  303,
       46,  135,   47,  302,  138,   48,  139,   49,   48,  135,
       50,  135,  301,   95,  225,   96,  140,   50,  147,  147,
      300,  147,  147,  226,  147,   97,  141,  215,  147,  216,
      299,  298,  298,  298,  298,   98,  147,  297,  147,  101,
      227,  162,  142,  150,  157,  150,  158,  159,  101,  228,
      297,   99,  143,  163,  160,  150,  297,  297,  164,  290,

      150,  100,  161,  150,  150,  135,  150,  296,  295,  150,
      157,  150,  165,  150,  294,  293,  292,  291,  150,  290,
      150,  290,  289,  287,  150,  150,  287,  287,  287,  150,
      286,  150,  147,   37,  286,   37,   37,   37,  150,   37,
       37,   37,   37,   37,   37,   37,  154,   37,  150,  286,
      166,  155,  286,  150,  285,  150,  215,  156,  216,  150,
      285,  285,  151,  285,  150,  150,  152,  167,  101,  150,
      150,  168,  150,  150,   37,  242,  150,  217,  276,  150,
      133,  150,  150,  150,  169,  132,  177,  150,  150,  170,
      150,  171,  133,  150,  150,  150,  132,  275,  150,  150,

       37,   37,   37,  274,   37,   37,   37,  273,   37,   37,
       37,   37,   37,   37,   37,  170,   37,  272,  150,  271,
      153,  180,  270,  269,  133,  132,  133,  178,  150,  132,
      154,  150,  268,  150,  179,  155,  150,  267,  150,  150,
      266,  156,  150,   37,  150,  265,  153,  180,  150,  186,
      262,  150,  182,  150,  262,  183,  262,  181,  184,  150,
      179,  187,  150,  262,  150,  133,  150,  185,  132,   37,
       37,  150,  150,  150,  172,  150,  249,  150,  182,  249,
      173,  150,  174,  249,  184,  150,  175,  176,  249,  150,
      150,  243,  150,  188,  189,  190,  150,  150,  242,  150,

      172,  150,  241,  235,  150,  215,  173,  216,  150,  234,
      150,  233,  191,  176,  192,  150,  232,  101,  150,  188,
      193,  190,  150,  206,  219,  194,  101,  150,  231,  150,
      195,  230,  229,  150,  150,  223,  222,  218,  191,  196,
      197,  150,  198,  237,  221,  150,  199,  200,  220,  219,
      214,  201,  238,  150,  202,  150,  150,  214,  204,  203,
      150,  205,  150,  150,  214,  214,  150,  150,  150,  239,
      208,  150,  150,  149,  150,  157,  150,  134,  240,  150,
      305,  131,  150,  127,  204,  203,  150,  150,  126,  105,
      151,  150,  123,  150,  152,  150,  162,  150,  150,  150,

      122,  157,  150,  158,  159,  150,  115,  150,  163,  150,
      150,  160,  107,  164,  150,  106,  150,  150,  305,  161,
      150,  150,  150,  305,  305,  150,  150,  305,  150,  150,
      165,  305,  305,  150,  305,  305,  150,  166,  150,  150,
      305,  150,  305,  305,  150,  167,  170,  150,  150,  168,
      150,  305,  150,  150,  179,  150,  180,  305,  305,  150,
      305,  305,  305,  305,  150,  305,  150,  169,  177,  305,
      305,  150,  170,  178,  171,  150,  305,  150,  172,  150,
      179,  305,  180,  305,  173,  150,  207,  305,  305,  150,
      150,  176,  182,  305,  150,  305,  150,  305,  184,  305,

      150,  150,  150,  186,  172,  150,  305,  150,  305,  305,
      173,  305,  174,  150,  305,  187,  175,  176,  182,  150,
      191,  183,  305,  252,  184,  190,  305,   37,  305,  150,
      150,  305,  305,  185,  150,  150,  305,  215,  252,  216,
      150,  150,  150,  305,  305,  150,  191,  305,  192,  101,
      189,  190,  150,  305,  193,  204,  305,  150,  101,  194,
      305,  150,  305,  150,  195,  150,   37,  305,  150,  263,
      305,  150,  305,  305,  305,  150,  150,  209,  305,  305,
      150,  204,  150,  203,  205,  210,  150,  150,  305,  196,
      197,  150,  198,  305,  252,  211,  199,  200,  305,  305,

      305,  201,  206,  305,  202,  264,  305,  216,  305,  203,
      305,  212,  135,  135,  305,  135,  135,  101,  135,  137,
      244,  213,  135,  208,  305,  305,  101,  305,  245,  305,
      135,  254,  135,  135,  135,  305,  135,  135,  246,  135,
      137,  255,  305,  135,  209,  305,  305,  305,  288,  305,
      216,  135,  258,  135,  247,  147,  147,  256,  147,  147,
      101,  147,  259,  305,  248,  147,  305,  257,   37,  101,
       37,   37,   37,  147,   37,  147,  251,   37,  260,   37,
       37,  243,   37,  244,  305,  305,  135,  305,  261,  277,
      305,  281,  305,  305,   37,  305,   37,   37,   37,  278,

       37,  282,  305,   37,  305,   37,   37,  135,   37,   37,
       37,  305,   37,   37,   37,  279,   37,  283,  251,   37,
      305,   37,   37,  305,   37,  280,  252,  284,  305,  147,
       37,  305,  305,  305,  305,   37,  305,  305,  305,  305,
      305,  252,  305,  305,  305,  305,  305,  305,  305,  305,
      305,   37,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,   37,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  252,   37,  305,

       37,   37,   39,  305,   39,  136,  305,  136,  136,  136,
      136,  136,  148,  305,  148,  148,  148,  148,  148,  150,
      305,  150,  150,  135,  305,  135,  135,  135,  135,  135,
      147,  305,  147,  147,  147,  147,  147,  250,  305,  250,
      250,  253,  253,  305,  253,  253,  252,  252,  305,  305,
      252,    3,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305
    } ;

static yyconst flex_int16_t yy_chk[1128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,    9,   11,    9,   11,
       12,   21,   11,   12,   14,   20,   14,   22,   14,   16,
       16,  313,   29,   24,   30,   22,   14,   24,   25,   21,

       20,    8,   25,   32,   25,   28,   14,   29,  312,   30,
        8,   32,   28,   35,   21,   36,  216,   35,  216,   36,
      309,   36,   14,   24,   40,   40,   51,    8,   41,   41,
       42,   42,   14,   43,   43,   51,    8,   13,   13,   13,
       13,   13,  301,   13,   13,   13,   13,   13,   13,   13,
      300,   13,  296,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   45,   45,   47,   45,   45,   47,   45,   45,  295,
       46,   45,   46,  294,   48,   46,   48,   49,   48,   45,
       49,   45,  293,   50,  119,   50,   48,   50,   52,   52,
      291,   52,   52,  119,   52,   50,   48,  101,   52,  101,
      289,  284,  283,  282,  281,   50,   52,  280,   52,  101,
      119,   57,   48,   57,   56,   56,   56,   56,  101,  119,
      279,   50,   48,   57,   56,   56,  278,  277,   57,  275,

       56,   50,   56,   58,   57,   45,   56,  274,  273,   57,
       56,   56,   58,   58,  272,  271,  270,  269,   58,  268,
       77,  267,  266,  261,   58,   77,  260,  259,  258,   58,
      257,   77,   52,   54,  256,   54,   54,   54,   59,   54,
       54,   54,   54,   54,   54,   54,   77,   54,   59,  255,
       59,   77,  254,   59,  248,   60,  102,   77,  102,   59,
      247,  246,   54,  245,   59,   60,   54,   60,  102,   61,
       60,   60,   63,   64,   54,  242,   60,  102,  241,   61,
      240,   60,   63,   64,   61,  239,   64,   63,   64,   61,
       61,   61,  238,   63,   64,   61,  237,  235,   63,   64,

       54,   54,   55,  234,   55,   55,   55,  233,   55,   55,
       55,   55,   55,   55,   55,   61,   55,  232,   65,  231,
       55,   66,  230,  229,  228,  227,  226,   65,   65,  225,
       55,   66,  223,   65,   65,   55,   66,  222,   67,   65,
      221,   55,   66,   55,   65,  220,   55,   66,   67,   69,
      213,   69,   68,   67,  212,   68,  211,   67,   68,   67,
       65,   69,   68,  210,   67,  146,   69,   68,  145,   55,
       55,   62,   69,   68,   62,   70,  143,   69,   68,  142,
       62,   62,   62,  141,   68,   70,   62,   62,  140,   71,
       70,  138,   62,   70,   71,   71,   70,   62,  135,   71,

       62,   70,  131,  129,   71,  103,   62,  103,   75,  128,
       71,  127,   72,   62,   72,   71,  126,  103,   75,   70,
       72,   71,   72,   75,  125,   72,  103,   72,  124,   75,
       72,  123,  122,   72,   75,  118,  117,  103,   72,   73,
       73,   73,   73,  130,  116,   74,   73,   73,  115,  113,
      100,   73,  130,   76,   73,   74,   73,   99,   74,   73,
       74,   74,   73,   76,   98,   97,   74,   73,   76,  130,
       95,   74,   79,   53,   76,   78,   78,   44,  130,   76,
       39,   38,   79,   34,   74,   73,   78,   79,   33,   31,
       76,   78,   27,   79,   76,   80,   79,   78,   79,   81,

       26,   78,   78,   78,   78,   80,   23,   82,   79,   81,
       80,   78,   19,   79,   81,   18,   80,   82,    3,   78,
       81,   80,   82,    0,    0,   81,   83,    0,   82,   85,
       80,    0,    0,   82,    0,    0,   83,   81,   86,   85,
        0,   83,    0,    0,   85,   82,   83,   83,   86,   82,
       85,    0,   83,   86,   86,   85,   87,    0,    0,   86,
        0,    0,    0,    0,   86,    0,   87,   83,   85,    0,
        0,   87,   83,   86,   83,   84,    0,   87,   84,   89,
       86,    0,   87,    0,   84,   84,   87,    0,    0,   89,
       84,   84,   88,    0,   89,    0,   84,    0,   88,    0,

       89,   84,   88,   89,   84,   89,    0,   88,    0,    0,
       84,    0,   84,   88,    0,   89,   84,   84,   88,   90,
       91,   88,    0,  207,   88,   90,    0,  207,    0,   90,
       91,    0,    0,   88,   90,   91,    0,  217,  207,  217,
       90,   91,   93,    0,    0,   90,   91,    0,   91,  217,
       90,   90,   93,    0,   91,   93,    0,   93,  217,   91,
        0,   94,    0,   93,   91,   92,  207,    0,   93,  217,
        0,   94,    0,    0,    0,   92,   94,   96,    0,    0,
       92,   93,   94,   92,   93,   96,   92,   94,    0,   92,
       92,   92,   92,    0,  207,   96,   92,   92,    0,    0,

        0,   92,   94,    0,   92,  218,    0,  218,    0,   92,
        0,   96,  136,  136,    0,  136,  136,  218,  136,  136,
      139,   96,  136,  208,    0,    0,  218,    0,  139,    0,
      136,  208,  136,  137,  137,    0,  137,  137,  139,  137,
      137,  208,    0,  137,  209,    0,    0,    0,  263,    0,
      263,  137,  209,  137,  139,  148,  148,  208,  148,  148,
      263,  148,  209,    0,  139,  148,    0,  208,  149,  263,
      149,  149,  149,  148,  149,  148,  149,  149,  209,  149,
      149,  243,  149,  244,    0,    0,  136,    0,  209,  243,
        0,  244,    0,    0,  250,    0,  250,  250,  250,  243,

      250,  244,    0,  250,    0,  250,  250,  137,  250,  149,
      251,    0,  251,  251,  251,  243,  251,  244,  251,  251,
        0,  251,  251,    0,  251,  243,  253,  244,    0,  148,
      253,    0,    0,    0,    0,  250,    0,    0,    0,    0,
        0,  253,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  251,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  253,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  253,  306,    0,

      306,  306,  307,    0,  307,  308,    0,  308,  308,  308,
      308,  308,  310,    0,  310,  310,  310,  310,  310,  311,
        0,  311,  311,  314,    0,  314,  314,  314,  314,  314,
      315,    0,  315,  315,  315,  315,  315,  316,    0,  316,
      316,  317,  317,    0,  317,  317,  318,  318,    0,    0,
      318,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[103] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
// \-                      { strcpy(yylval.tokens, yytext); printf("NEG %s\n", yytext); return NEG_T;}

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "y.tab.h"

#line 856 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 13 "lex.l"



#line 1078 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 306 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1052 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 16 "lex.l"
{ strcpy(yylval.tokens, yytext); return BR_T;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 17 "lex.l"
{ strcpy(yylval.tokens, yytext); return NV_T;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 18 "lex.l"
{ strcpy(yylval.tokens, yytext); return PAGE_T;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 19 "lex.l"
{ strcpy(yylval.tokens, yytext); return NY_T;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 20 "lex.l"
{ strcpy(yylval.tokens, yytext); return ENY_T;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 21 "lex.l"
{ strcpy(yylval.tokens, yytext); return COMMENT_T;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 22 "lex.l"
{ strcpy(yylval.tokens, yytext); return TI_T;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 23 "lex.l"
{ strcpy(yylval.tokens, yytext); return IN_T;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 24 "lex.l"
{ strcpy(yylval.tokens, yytext); return IR_T;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 25 "lex.l"
{ strcpy(yylval.tokens, yytext); return DA_T;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 26 "lex.l"
{ strcpy(yylval.tokens, yytext); return FO_T;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 27 "lex.l"
{ strcpy(yylval.tokens, yytext); return ON_T;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 28 "lex.l"
{ strcpy(yylval.tokens, yytext); return GOTO_T;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 29 "lex.l"
{ strcpy(yylval.tokens, yytext); return LL_T;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 30 "lex.l"
{ strcpy(yylval.tokens, yytext); return RH_T;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 31 "lex.l"
{ strcpy(yylval.tokens, yytext); return CT_T;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 32 "lex.l"
{ strcpy(yylval.tokens, yytext); return PA_T;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 33 "lex.l"
{ strcpy(yylval.tokens, yytext); return DR_T;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 34 "lex.l"
{ strcpy(yylval.tokens, yytext); return WEIGHT_T;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 35 "lex.l"
{ strcpy(yylval.tokens, yytext); return KP_T;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 36 "lex.l"
{ strcpy(yylval.tokens, yytext); return EXECUTE_T;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 37 "lex.l"
{ strcpy(yylval.tokens, yytext); return IF_T;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 38 "lex.l"
{ strcpy(yylval.tokens, yytext); return RI_T;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 39 "lex.l"
{ strcpy(yylval.tokens, yytext); return OI_T;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 40 "lex.l"
{ strcpy(yylval.tokens, yytext); return CB_T;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 41 "lex.l"
{ strcpy(yylval.tokens, yytext); return SC_T;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 42 "lex.l"
{ strcpy(yylval.tokens, yytext); return MC_T;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 43 "lex.l"
{ strcpy(yylval.tokens, yytext); return QU_T;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 44 "lex.l"
{ strcpy(yylval.tokens, yytext); return HW_T;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 45 "lex.l"
{ strcpy(yylval.tokens, yytext); return IL_T;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 46 "lex.l"
{ strcpy(yylval.tokens, yytext); return OC_T;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 47 "lex.l"
{ strcpy(yylval.tokens, yytext); return BC_T;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 48 "lex.l"
{ strcpy(yylval.tokens, yytext); return IS_T;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 49 "lex.l"
{ strcpy(yylval.tokens, yytext); return UP_T;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 50 "lex.l"
{ strcpy(yylval.tokens, yytext); return LS_T;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 51 "lex.l"
{ strcpy(yylval.tokens, yytext); return TU_T;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 52 "lex.l"
{ strcpy(yylval.tokens, yytext); return EL_T;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 53 "lex.l"
{ strcpy(yylval.tokens, yytext); return TH_T;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 54 "lex.l"
{ strcpy(yylval.tokens, yytext); return OR_T;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 55 "lex.l"
{ strcpy(yylval.tokens, yytext); return CD_T;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 56 "lex.l"
{ strcpy(yylval.tokens, yytext); return TD_T;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 57 "lex.l"
{ strcpy(yylval.tokens, yytext); return SU_T;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 58 "lex.l"
{ strcpy(yylval.tokens, yytext); return DM_T;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 59 "lex.l"
{ strcpy(yylval.tokens, yytext); return GS_T;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 60 "lex.l"
{ strcpy(yylval.tokens, yytext); return TB_T;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 61 "lex.l"
{ strcpy(yylval.tokens, yytext); return SK_T;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 62 "lex.l"
{ strcpy(yylval.tokens, yytext); return CE_T;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 63 "lex.l"
{ strcpy(yylval.tokens, yytext); return CL_T;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 64 "lex.l"
{ strcpy(yylval.tokens, yytext); return AN_T;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 65 "lex.l"
{ strcpy(yylval.tokens, yytext); return OF_T;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 66 "lex.l"
{ strcpy(yylval.tokens, yytext); return HR_T;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 67 "lex.l"
{ strcpy(yylval.tokens, yytext); return VR_T;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 68 "lex.l"
{ strcpy(yylval.tokens, yytext); return HY_T;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 69 "lex.l"
{ strcpy(yylval.tokens, yytext); return NOTEQUAL_T;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 70 "lex.l"
{ strcpy(yylval.tokens, yytext); return EQUAL_T;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 71 "lex.l"
{ strcpy(yylval.tokens, yytext); return GTHAN_T;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 72 "lex.l"
{ strcpy(yylval.tokens, yytext); return LTHAN_T;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 73 "lex.l"
{ strcpy(yylval.tokens, yytext); return GTHANE_T;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 74 "lex.l"
{ strcpy(yylval.tokens, yytext); return LTHANE_T;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 75 "lex.l"
{ strcpy(yylval.tokens, yytext); return OFF_T;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 76 "lex.l"
{ strcpy(yylval.tokens, yytext); return UPPERCASE_T;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 77 "lex.l"
{ strcpy(yylval.tokens, yytext); return LENGTH_T;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 78 "lex.l"
{ strcpy(yylval.tokens, yytext); return AR_T;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 79 "lex.l"
{ strcpy(yylval.tokens, yytext); return BX_T;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 80 "lex.l"
{ strcpy(yylval.tokens, yytext); return SP_T;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 81 "lex.l"
{ strcpy(yylval.tokens, yytext); return SE_T;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 82 "lex.l"
{ strcpy(yylval.tokens, yytext); return US_T;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 83 "lex.l"
{ strcpy(yylval.tokens, yytext); return TM_T;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 84 "lex.l"
{ strcpy(yylval.tokens, yytext); return BM_T;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 85 "lex.l"
{ strcpy(yylval.tokens, yytext); return PM_T;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 86 "lex.l"
{ strcpy(yylval.tokens, yytext); return WIDTH_T;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 87 "lex.l"
{ strcpy(yylval.tokens, yytext); return TP_T;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 88 "lex.l"
{ strcpy(yylval.tokens, yytext); return TA_T;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 89 "lex.l"
{ strcpy(yylval.tokens, yytext); return ROTATE_T;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 90 "lex.l"
{ strcpy(yylval.tokens, yytext); return DEPTH_T;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 91 "lex.l"
{ strcpy(yylval.tokens, yytext); return SUBSTR_T;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 92 "lex.l"
{ strcpy(yylval.tokens, yytext); return MF_T;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 93 "lex.l"
{ strcpy(yylval.tokens, yytext); return UNKNOWN_T;}
	YY_BREAK
case 79:
#line 95 "lex.l"
case 80:
YY_RULE_SETUP
#line 95 "lex.l"
{ strcpy(yylval.tokens, yytext); return SIZE_T;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 96 "lex.l"
{ strcpy(yylval.tokens, yytext); return SIZE_T;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 97 "lex.l"
{ strcpy(yylval.tokens, yytext); return SIZE_T;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 98 "lex.l"
{ strcpy(yylval.tokens, yytext); return SIZE_T;}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 99 "lex.l"
{ strcpy(yylval.tokens, yytext); return NEW_LINE_T; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 100 "lex.l"
{ strcpy(yylval.tokens, yytext); return STYLE_T;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 101 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_UP_T;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 102 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_T;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 103 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_T;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 104 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_T;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 105 "lex.l"
{ strcpy(yylval.tokens, yytext); return VAR_T;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 106 "lex.l"
{ strcpy(yylval.tokens, yytext); return NUM_T;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 107 "lex.l"
{ strcpy(yylval.tokens, yytext); return NUM_T;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 108 "lex.l"
{ strcpy(yylval.tokens, yytext); return NUM_T;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 109 "lex.l"
{ strcpy(yylval.tokens, yytext); return IDENT_T;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 110 "lex.l"
{ strcpy(yylval.tokens, yytext); return LABEL_T;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 111 "lex.l"
{ strcpy(yylval.tokens, yytext); return MATHEX_T;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 112 "lex.l"
{ strcpy(yylval.tokens, yytext); return IDENT_T;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 113 "lex.l"
{ strcpy(yylval.tokens, yytext); return MATHEX_T;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 114 "lex.l"
{ strcpy(yylval.tokens, yytext); return IDENT_T;}                  
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 115 "lex.l"
{ strcpy(yylval.tokens, yytext); return IDENT_T;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 116 "lex.l"
;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 117 "lex.l"
ECHO;
	YY_BREAK
#line 1653 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 306 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 306 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 305);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 117 "lex.l"




int yywrap(void){
    return 1;
}


    

